name: 'Javadoc_evaluator'
description: 'A tool to check whether the documentation is sufficient'
author: 'Timo Schoemaker'
inputs:
  global_threshold:
    description: "The global threshold when to fail"
    required: false
branding:
  icon: 'check-circle'
  color: 'blue'
runs:
  using: 'node16'
  pre: "tsc"
  main: 'build/src/index.js'
  